# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  check-project:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/openjdk:21.0.0
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Project checkout"
          command: "echo Checking out project"

  build-project:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout

      # Install Maven
      - run:
          name: Install Maven
          command: |
            MAVEN_VERSION=3.9.6
            MAVEN_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
            curl -fsSL ${MAVEN_URL} | tar -xvzf C:\Users\user\Downloads\apache-maven-3.9.6.tar.gz -C C:\opt
            export PATH="/opt/apache-maven-${MAVEN_VERSION}/bin:$PATH"

      # Your build commands using Maven
      - run:
          name: Build with Maven
          command: mvn clean install

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  project-build-workflow:
    jobs:
      - check-project
      - build-project
